package com.springboot.demo.mapper;

import com.springboot.demo.model.Game;

import java.util.Date;

public interface GameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    int insert(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    int insertSelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    Game selectByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Game record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Game record);
}