package com.springboot.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Game implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.game.Date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.game.USD
     *
     * @mbg.generated
     */
    private BigDecimal usd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.game.TYPE
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    public Game(Date date, BigDecimal usd, String type) {
        this.date = date;
        this.usd = usd;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    public Game() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.game.Date
     *
     * @return the value of dbo.game.Date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.game.Date
     *
     * @param date the value for dbo.game.Date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.game.USD
     *
     * @return the value of dbo.game.USD
     *
     * @mbg.generated
     */
    public BigDecimal getUsd() {
        return usd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.game.USD
     *
     * @param usd the value for dbo.game.USD
     *
     * @mbg.generated
     */
    public void setUsd(BigDecimal usd) {
        this.usd = usd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.game.TYPE
     *
     * @return the value of dbo.game.TYPE
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.game.TYPE
     *
     * @param type the value for dbo.game.TYPE
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.game
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", date=").append(date);
        sb.append(", usd=").append(usd);
        sb.append(", type=").append(type);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}